package hol2eih4;

public class SqlHolder {

	public static String bedDayMySql = 
""
+"			SELECT d.*,"
+"		       if(d.dead IS NULL, 0, d.dead/TREAT*100) mortality"
+"		FROM"
+"		  (SELECT d.*,"
+"		          (d.in_clinic+ifnull(d.in_dep,0)+d.out_clinic+ifnull(d.out_dep,0)+ifnull(d.dead,0))/2 treat"
+"		   FROM"
+"		     (SELECT d.department_id dp_id,"
+"		             d.department_name,"
+"		             d.department_bed,"
+"		             in_clinic.in_clinic,"
+"		             in_dep.in_dep,"
+"		             out_clinic.out_clinic,"
+"		             out_dep.out_dep,"
+"		             out_to_clinic.out_to_clinic,"
+"		             dead.dead,"
+"		             bed_day.bed_day"
+"		      FROM"
+"		        (SELECT d.department_id,"
+"		                d.department_name,"
+"		                db.department_bed"
+"		         FROM department d,"
+"		           (SELECT department_id,"
+"		                   max(department_bed_start),"
+"		                   department_bed"
+"		            FROM department_bed"
+"		            GROUP BY department_id) db"
+"		         WHERE d.department_id=db.department_id) d"
+"		      LEFT JOIN"
+"		        (SELECT history_department_in,"
+"		                count(history_department_in) in_clinic"
+"		         FROM history"
+"		         WHERE month(history_in) = 1"
+"		           AND year(history_in)=2016"
+"		         GROUP BY history_department_in) in_clinic ON in_clinic.history_department_in=d.department_id"
+"		      LEFT JOIN"
+"		        (SELECT dh.department_id,"
+"		                count(dh.department_id) in_dep"
+"		         FROM"
+"		           (SELECT dh.*"
+"		            FROM department_history dh,"
+"		                 history h"
+"		            WHERE h.history_id=dh.history_id"
+"		              AND h.history_department_in != dh.department_id) dh"
+"		         WHERE month(dh.department_history_in) = 1"
+"		           AND year(dh.department_history_in)=2016"
+"		         GROUP BY dh.department_id) in_dep ON in_dep.department_id=d.department_id"
+"		      LEFT JOIN"
+"		        (SELECT history_department_out,"
+"		                count(history_department_out) out_clinic"
+"		         FROM history"
+"		         WHERE month(history_out)=1"
+"		           AND year(history_out)=2016"
+"		         GROUP BY history_department_out) out_clinic ON out_clinic.history_department_out=d.department_id"
+"		      LEFT JOIN"
+"		        (SELECT dh.department_id,"
+"		                count(dh.department_id) out_dep"
+"		         FROM"
+"		           (SELECT dh.*"
+"		            FROM department_history dh,"
+"		                 history h"
+"		            WHERE h.history_id=dh.history_id"
+"		              AND h.history_department_out != dh.department_id) dh"
+"		         WHERE month(dh.department_history_out)=1"
+"		           AND year(dh.department_history_out)=2016"
+"		         GROUP BY dh.department_id) out_dep ON out_dep.department_id=d.department_id"
+"		      LEFT JOIN"
+"		        (SELECT history_department_out,"
+"		                count(history_department_out) out_to_clinic"
+"		         FROM history h"
+"		         WHERE result_id=6"
+"		           AND month(history_out)=1"
+"		           AND year(history_out)=2016"
+"		         GROUP BY history_department_out) out_to_clinic ON out_to_clinic.history_department_out=d.department_id"
+"		      LEFT JOIN"
+"		        (SELECT history_department_out,"
+"		                count(history_department_out) dead"
+"		         FROM history"
+"		         WHERE month(history_out)=1"
+"		           AND year(history_out)=2016"
+"		           AND result_id=5"
+"		         GROUP BY history_department_out) dead ON dead.history_department_out=d.department_id"
+"		      LEFT JOIN"
+"		        ( SELECT department_id,"
+"		                 sum(TREAT) bed_day"
+"		         FROM"
+"		           (SELECT department_id,"
+"		                   daydate,"
+"		                   count(daydate) TREAT"
+"		            FROM department_history dh,"
+"		              (SELECT *"
+"		               FROM every_day"
+"		               WHERE month(daydate) = 1"
+"		                 AND year(daydate) = 2016) daydate"
+"		            WHERE daydate>=dh.department_history_in"
+"		              AND daydate<=dh.department_history_out"
+"		            GROUP BY department_id,"
+"		                     daydate) treat_of_day"
+"		         GROUP BY department_id ) bed_day ON bed_day.department_id=d.department_id ) d)d"
+"		UNION"
+"		SELECT *"
+"		FROM"
+"		  (SELECT 0 dp_id,"
+"		          'Всього:' department_name,"
+"		                    0 d_bed) all_,"
+"		  (SELECT count(history_department_in) _in"
+"		   FROM history"
+"		   WHERE month(history_in)=1"
+"		     AND year(history_in)=2016) in_,"
+"		  (SELECT 0 in_dep) in_dep,"
+"		  (SELECT count(history_department_out) _out"
+"		   FROM history"
+"		   WHERE month(history_out)=1"
+"		     AND year(history_out)=2016) out_,"
+"		  (SELECT 0 out_dep) out_dep,"
+"		  (SELECT 0 out_to_clinic) out_to_clinic,"
+"		  (SELECT count(history_department_out) dead,"
+"		     (SELECT 0 l) bed_day,"
+"		     (SELECT 0 l) TREAT,"
+"		     (SELECT 0 l) mortality"
+"		   FROM history"
+"		   WHERE month(history_out)=1"
+"		     AND year(history_out)=2016"
+"		     AND result_id=5) dead"
+"";
	public static String bedDayH2 = ""
			+" SELECT calc3.*, "
			+"        round(bed_occupancy/treat_avg,2) bed_turnover "
			+" FROM "
			+"   (SELECT calc2.*, "
			+"           bed_day*100/bed_day_plan bed_day_fulfil, "
			+"           bed_day*10/DEPARTMENT_BED*.1 bed_occupancy, "
			+"           TREAT*1000/bed_day*.1 treat_avg "
			+"    FROM "
			+"      (SELECT calc1.*, "
			+"              ifnull(dead,0)*1000/TREAT*.1 mortality_procent, "
			+"                                        ym.k*100/ym.yd*ym.month_days*DEPARTMENT_bed/100 bed_day_plan "
			+"       FROM "
			+"         (SELECT d.DEPARTMENT_id dp_id, "
			+"                 d.DEPARTMENT_name, "
			+"                 d.DEPARTMENT_bed, "
			+"                 summ.*, "
			+"                 (summ.in_clinic+ifnull(summ.in_department,0)+ summ.out_clinic + ifnull(summ.out_department,0) + ifnull(summ.dead,0))/2 TREAT "
			+"          FROM hol2.DEPARTMENT d "
			+"          LEFT JOIN "
			+"            (SELECT sum(MOVEDEPARTMENTPATIENT_IN) in_clinic, "
			+"                    sum(MOVEDEPARTMENTPATIENT_INDEPARTMENT) in_department, "
			+"                    sum(MOVEDEPARTMENTPATIENT_OUT) out_clinic, "
			+"                    sum(MOVEDEPARTMENTPATIENT_OUTDEPARTMENT) out_department, "
			+"                    sum(MOVEDEPARTMENTPATIENT_DEAD) dead, "
			+"                    sum(MOVEDEPARTMENTPATIENT_PATIENT2DAY) bed_day, "
			+"                    DEPARTMENT_ID "
			+"             FROM hol2.MOVEDEPARTMENTPATIENT "
			+"             WHERE month(MOVEDEPARTMENTPATIENT_DATE)>=1 "
			+"               AND month(MOVEDEPARTMENTPATIENT_DATE)<=1 "
			+"               AND year(MOVEDEPARTMENTPATIENT_DATE)=2016 "
			+"             GROUP BY DEPARTMENT_ID) summ ON d.DEPARTMENT_id=summ.DEPARTMENT_id "
			+"          ORDER BY d.DEPARTMENT_id) calc1, "
			+"         (SELECT day(dateadd(dd,-day(ym_next),ym_next)) month_days, "
			+"                 CASE WHEN 2016%4 =0 THEN 366 ELSE 365 END yd, "
			+"                                                           280 k "
			+"          FROM "
			+"            (SELECT DATEADD(m,1,ym) ym_next "
			+"             FROM "
			+"               (SELECT parsedatetime(concat(2016,'-',1,'-1'),'yyyy-MM-dd') ym)ym)ym)ym) calc2)calc3 "
;

}
