package hol2eih4;

public class SqlHolder {

	public static String icd10K1 = ""
			+" SELECT * FROM( \n"
			+" SELECT iall.*,  \n"
			+"         imn.cnt  \n"
			+"  FROM  \n"
			+"    (SELECT ICD_CODE,  \n"
			+"            icd_name  \n"
			+"     FROM dity1.ix ix,  \n"
			+"          list.icd icd  \n"
			+"     WHERE ix.ICD_CODE1=ICD_CODE  \n"
			+"     GROUP BY ICD_CODE) iall  \n"
			+"  LEFT JOIN  \n"
			+"    (SELECT ICD_CODE,  \n"
			+"            count(ICD_CODE) cnt  \n"
			+"     FROM  \n"
			+"       (SELECT *  \n"
			+"        FROM dity1.ix  \n"
			+"        WHERE month(ix_out)  >= :min_month    \n"
			+"          AND month(ix_out)  <= :max_month ) ix,  \n"
			+"          list.icd icd  \n"
			+"     WHERE ix.ICD_CODE1=ICD_CODE  \n"
			+"     GROUP BY ICD_CODE ) imn ON iall.icd_code=imn.icd_code ) s1 \n"
//			+" union \n"
//			+" SELECT * FROM \n"
//			+" (SELECT concat(icd_code_group,'_Всього'),'',sum_icd_group FROM  \n"
//			+" (SELECT icd_code_group, count(icd_code_group) cnt_icd_group, sum(cnt) sum_icd_group FROM ( \n"
//			+" SELECT ICD_CODE, substr(icd_code,1,3) icd_code_group, \n"
//			+"           count(ICD_CODE) cnt \n"
//			+"    FROM \n"
//			+"      (SELECT * \n"
//			+"       FROM dity1.ix \n"
//			+"       WHERE month(ix_out) >= :min_month  \n"
//			+"         AND month(ix_out) <= :max_month ) ix, \n"
//			+"         list.icd icd \n"
//			+"    WHERE ix.ICD_CODE1=ICD_CODE \n"
//			+"    GROUP BY ICD_CODE) icd_code_group \n"
//			+"    group by icd_code_group) cnt_icd_group \n"
//			+"    where cnt_icd_group > 1) s2 \n"
			+"  UNION  \n"
			+"  SELECT * FROM ( \n"
			+"  SELECT 'Всього',  \n"
			+"         '',  \n"
			+"         count(*) cnt  \n"
			+"  FROM  \n"
			+"    (SELECT *  \n"
			+"     FROM dity1.ix  \n"
			+"     WHERE month(ix_out)  >= :min_month  \n"
			+"       AND month(ix_out)  <= :max_month ) ix,  \n"
			+"       list.icd icd  \n"
			+"  WHERE ix.ICD_CODE1=ICD_CODE ) s3 \n"
			+"   \n"
			+"  ORDER BY iall.icd_code  \n"
			+"  \n"
;
	
	public static String departmentIcd10 = ""
			+" SELECT all_icd10_of_department.*, misto_cnt, misto_bed_day, selo_cnt, selo_bed_day \n"
			+" , referral_has.* , referral_self.* , referral_hol.*  \n"
			+" , remove_hol.* , remove_true.*, remove_dead.* \n"
			+" FROM ( \n"
			+" SELECT icd_code, \n"
			+"        count(icd_code) cnt_all_icd, \n"
			+"        icd_name , icd_id \n"
			+"        FROM \n"
			+"   (SELECT icd.*, dh.history_id \n"
			+"    FROM history_diagnos hd, department_history dh, icd icd \n"
			+"    WHERE hd.history_id=dh.history_id \n"
			+"      AND department_id = :department_id  \n"
			+"      AND diagnos_id=3 \n"
			+"      AND hd.icd_id=icd.icd_id) all_department_history_with_diagnose \n"
			+" GROUP BY icd_code) all_icd10_of_department \n"
			+" LEFT JOIN ( \n"
			+" SELECT locality_type misto, \n"
			+"        count(locality_type) misto_cnt, \n"
			+"        icd_id, \n"
			+"        icd_code, \n"
			+"        sum(bed_day) misto_bed_day \n"
			+" FROM \n"
			+"   (SELECT * \n"
			+"    FROM \n"
			+"      (SELECT datediff(department_history_out, department_history_in)+1 bed_day, department_history_period.*, \n"
			+"              all_department_history_with_icd10.*, \n"
			+"              h.patient_id patient_id_h \n"
			+"       FROM history h, \n"
			+"         (SELECT * \n"
			+"          FROM department_history \n"
			+"          WHERE department_id = :department_id  \n"
			+"            AND YEAR(department_history_out)  = :year  \n"
			+"            AND MONTH(department_history_out)  >= :min_month  \n"
			+"            AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+" 	LEFT JOIN ( \n"
			+" 	SELECT icd.*, \n"
			+"                 dh.history_id h2_id \n"
			+"          FROM history_diagnos hd, \n"
			+"               department_history dh, \n"
			+"               icd icd \n"
			+"          WHERE hd.history_id=dh.history_id \n"
			+"            AND department_id = :department_id  \n"
			+"            AND diagnos_id=3 \n"
			+"            AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"       WHERE department_history_period.history_id= h.history_id) history_icd10, \n"
			+"      (SELECT patient_id patient_id_p, \n"
			+"              locality_id locality_id_p \n"
			+"       FROM patient) p, \n"
			+"         locality l \n"
			+"    WHERE patient_id_p=patient_id_h \n"
			+"      AND locality_id_p=l.locality_id) misto_selo \n"
			+" GROUP BY icd_id, \n"
			+"          locality_type) misto on all_icd10_of_department.icd_id=misto.icd_id and misto=1 \n"
			+" LEFT JOIN ( \n"
			+" SELECT locality_type selo_misto, \n"
			+"        count(locality_type) selo_cnt, \n"
			+"        icd_id, \n"
			+"        icd_code, \n"
			+"        sum(bed_day) selo_bed_day \n"
			+" FROM \n"
			+"   (SELECT * \n"
			+"    FROM \n"
			+"      (SELECT datediff(department_history_out, department_history_in)+1 bed_day, department_history_period.*, \n"
			+"              all_department_history_with_icd10.*, \n"
			+"              h.patient_id patient_id_h \n"
			+"       FROM history h, \n"
			+"         (SELECT * \n"
			+"          FROM department_history \n"
			+"          WHERE department_id = :department_id  \n"
			+"            AND YEAR(department_history_out)  = :year  \n"
			+"            AND MONTH(department_history_out)  >= :min_month  \n"
			+"            AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"       LEFT JOIN \n"
			+"         (SELECT icd.*, \n"
			+"                 dh.history_id h2_id \n"
			+"          FROM history_diagnos hd, \n"
			+"               department_history dh, \n"
			+"               icd icd \n"
			+"          WHERE hd.history_id=dh.history_id \n"
			+"            AND department_id = :department_id  \n"
			+"            AND diagnos_id=3 \n"
			+"            AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id  \n"
			+"       WHERE department_history_period.history_id= h.history_id) history_icd10, \n"
			+"      (SELECT patient_id patient_id_p, \n"
			+"              locality_id locality_id_p \n"
			+"       FROM patient) p, \n"
			+"         locality l \n"
			+"    WHERE patient_id_p=patient_id_h \n"
			+"      AND locality_id_p=l.locality_id) misto_selo \n"
			+" GROUP BY icd_id, \n"
			+"          locality_type) selo on all_icd10_of_department.icd_id=selo.icd_id and selo_misto=0 \n"
			+" LEFT JOIN ( \n"
			+" SELECT referral_cnt  referral_has_cnt, referral_bed_day_sum referral_has_bed_day, icd_id referral_has_icd_id  \n"
			+" FROM \n"
			+"   (SELECT referral.*, \n"
			+"           COUNT(referral) referral_cnt, \n"
			+"           SUM(referral_bed_day) referral_bed_day_sum \n"
			+"    FROM \n"
			+"      (SELECT icd_id, \n"
			+"              icd_code, \n"
			+"              IF(dr.direct_id=1,1,IF(dhf.department_id > 0,99999,0)) referral, \n"
			+"              datediff(history_icd10.department_history_out, history_icd10.department_history_in)+1 referral_bed_day \n"
			+"       FROM \n"
			+"         (SELECT department_history_period.*, \n"
			+"                 all_department_history_with_icd10.*, \n"
			+"                 h.direct_id \n"
			+"          FROM patient p, \n"
			+"               history h, \n"
			+"            (SELECT * \n"
			+"             FROM department_history \n"
			+"             WHERE department_id = :department_id  \n"
			+"               AND YEAR(department_history_out)  = :year  \n"
			+"               AND MONTH(department_history_out)  >= :min_month  \n"
			+"               AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"          LEFT JOIN \n"
			+"            (SELECT icd.icd_id, \n"
			+"                    icd.icd_code, \n"
			+"                    icd.icd_name, \n"
			+"                    dh.history_id h2_id \n"
			+"             FROM history_diagnos hd, \n"
			+"                  department_history dh, \n"
			+"                  icd icd \n"
			+"             WHERE hd.history_id=dh.history_id \n"
			+"               AND department_id = :department_id  \n"
			+"               AND diagnos_id=3 \n"
			+"               AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"          WHERE p.patient_id=h.patient_id \n"
			+"            AND department_history_period.history_id= h.history_id) history_icd10 \n"
			+"       LEFT JOIN department_history dhf ON history_icd10.h2_id = dhf.history_id \n"
			+"       AND TIMESTAMPDIFF(SECOND,dhf.department_history_out, history_icd10.department_history_in) = 1, \n"
			+"                                                                                                   direct dr \n"
			+"       WHERE dr.direct_id=history_icd10.direct_id ) referral \n"
			+"    GROUP BY icd_code, \n"
			+"             referral) referral \n"
			+" WHERE referral=1) referral_has on referral_has_icd_id = all_icd10_of_department.icd_id \n"
			+" LEFT JOIN ( \n"
			+" SELECT referral_cnt  referral_self_cnt, referral_bed_day_sum referral_self_bed_day, icd_id referral_self_icd_id  \n"
			+" FROM \n"
			+"   (SELECT referral.*, \n"
			+"           COUNT(referral) referral_cnt, \n"
			+"           SUM(referral_bed_day) referral_bed_day_sum \n"
			+"    FROM \n"
			+"      (SELECT icd_id, \n"
			+"              icd_code, \n"
			+"              IF(dr.direct_id=1,1,IF(dhf.department_id > 0,99999,0)) referral, \n"
			+"              datediff(history_icd10.department_history_out, history_icd10.department_history_in)+1 referral_bed_day \n"
			+"       FROM \n"
			+"         (SELECT department_history_period.*, \n"
			+"                 all_department_history_with_icd10.*, \n"
			+"                 h.direct_id \n"
			+"          FROM patient p, \n"
			+"               history h, \n"
			+"            (SELECT * \n"
			+"             FROM department_history \n"
			+"             WHERE department_id = :department_id  \n"
			+"               AND YEAR(department_history_out)  = :year  \n"
			+"               AND MONTH(department_history_out)  >= :min_month  \n"
			+"               AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"          LEFT JOIN \n"
			+"            (SELECT icd.icd_id, \n"
			+"                    icd.icd_code, \n"
			+"                    icd.icd_name, \n"
			+"                    dh.history_id h2_id \n"
			+"             FROM history_diagnos hd, \n"
			+"                  department_history dh, \n"
			+"                  icd icd \n"
			+"             WHERE hd.history_id=dh.history_id \n"
			+"               AND department_id = :department_id  \n"
			+"               AND diagnos_id=3 \n"
			+"               AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"          WHERE p.patient_id=h.patient_id \n"
			+"            AND department_history_period.history_id= h.history_id) history_icd10 \n"
			+"       LEFT JOIN department_history dhf ON history_icd10.h2_id = dhf.history_id \n"
			+"       AND TIMESTAMPDIFF(SECOND,dhf.department_history_out, history_icd10.department_history_in) = 1, \n"
			+"                                                                                                   direct dr \n"
			+"       WHERE dr.direct_id=history_icd10.direct_id ) referral \n"
			+"    GROUP BY icd_code, \n"
			+"             referral) referral \n"
			+" WHERE referral=0) referral_self on referral_self_icd_id = all_icd10_of_department.icd_id \n"
			+" LEFT JOIN ( \n"
			+" SELECT referral_cnt  referral_hol_cnt, referral_bed_day_sum referral_hol_bed_day, icd_id referral_hol_icd_id  \n"
			+" FROM \n"
			+"   (SELECT referral.*, \n"
			+"           COUNT(referral) referral_cnt, \n"
			+"           SUM(referral_bed_day) referral_bed_day_sum \n"
			+"    FROM \n"
			+"      (SELECT icd_id, \n"
			+"              icd_code, \n"
			+"              IF(dr.direct_id=1,1,IF(dhf.department_id > 0,99999,0)) referral, \n"
			+"              datediff(history_icd10.department_history_out, history_icd10.department_history_in)+1 referral_bed_day \n"
			+"       FROM \n"
			+"         (SELECT department_history_period.*, \n"
			+"                 all_department_history_with_icd10.*, \n"
			+"                 h.direct_id \n"
			+"          FROM patient p, \n"
			+"               history h, \n"
			+"            (SELECT * \n"
			+"             FROM department_history \n"
			+"             WHERE department_id = :department_id  \n"
			+"               AND YEAR(department_history_out)  = :year  \n"
			+"               AND MONTH(department_history_out)  >= :min_month  \n"
			+"               AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"          LEFT JOIN \n"
			+"            (SELECT icd.icd_id, \n"
			+"                    icd.icd_code, \n"
			+"                    icd.icd_name, \n"
			+"                    dh.history_id h2_id \n"
			+"             FROM history_diagnos hd, \n"
			+"                  department_history dh, \n"
			+"                  icd icd \n"
			+"             WHERE hd.history_id=dh.history_id \n"
			+"               AND department_id = :department_id  \n"
			+"               AND diagnos_id=3 \n"
			+"               AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"          WHERE p.patient_id=h.patient_id \n"
			+"            AND department_history_period.history_id= h.history_id) history_icd10 \n"
			+"       LEFT JOIN department_history dhf ON history_icd10.h2_id = dhf.history_id \n"
			+"       AND TIMESTAMPDIFF(SECOND,dhf.department_history_out, history_icd10.department_history_in) = 1, \n"
			+"                                                                                                   direct dr \n"
			+"       WHERE dr.direct_id=history_icd10.direct_id ) referral \n"
			+"    GROUP BY icd_code, \n"
			+"             referral) referral \n"
			+" WHERE referral>1) referral_hol on referral_hol_icd_id = all_icd10_of_department.icd_id \n"
			+" LEFT JOIN ( \n"
			+" SELECT remove_icd_id remove_hol_icd_id, remove_cnt_x  remove_hol_cnt, remove_bed_day_x remove_hol_bed_day FROM ( \n"
			+" SELECT icd_id remove_icd_id,icd_code remove_icd_code, remove, count(remove) remove_cnt_x, sum(remove_bed_day) remove_bed_day_x \n"
			+" FROM \n"
			+"   (SELECT history_icd10.icd_id, \n"
			+"           history_icd10.icd_code, \n"
			+"           if(remove_to.history_id>0,7,if(result_id=5,9,8)) remove, \n"
			+"           datediff(history_icd10.department_history_out, history_icd10.department_history_in)+1 remove_bed_day \n"
			+"    FROM \n"
			+"      (SELECT department_history_period.*, \n"
			+"              all_department_history_with_icd10.*, \n"
			+"              h.direct_id, \n"
			+"              h.result_id \n"
			+"       FROM patient p, \n"
			+"            history h, \n"
			+"         (SELECT * \n"
			+"          FROM department_history \n"
			+"          WHERE department_id = :department_id  \n"
			+"            AND YEAR(department_history_out)  = :year  \n"
			+"            AND MONTH(department_history_out)  >= :min_month  \n"
			+"            AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"       LEFT JOIN \n"
			+"         (SELECT icd.icd_id, \n"
			+"                 icd.icd_code, \n"
			+"                 icd.icd_name, \n"
			+"                 dh.history_id h2_id \n"
			+"          FROM history_diagnos hd, \n"
			+"               department_history dh, \n"
			+"               icd icd \n"
			+"          WHERE hd.history_id=dh.history_id \n"
			+"            AND department_id = :department_id  \n"
			+"            AND diagnos_id=3 \n"
			+"            AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"       WHERE p.patient_id=h.patient_id \n"
			+"         AND department_history_period.history_id= h.history_id) history_icd10 \n"
			+"    LEFT JOIN department_history remove_to ON history_icd10.history_id = remove_to.history_id \n"
			+"    AND TIMESTAMPDIFF(SECOND,history_icd10.department_history_out,remove_to.department_history_in) = 1 \n"
			+"    ) remove \n"
			+"    GROUP BY icd_id, remove) remove \n"
			+"      WHERE remove = 7 \n"
			+" ) remove_hol on remove_hol_icd_id = all_icd10_of_department.icd_id \n"
			+" LEFT JOIN ( \n"
			+" SELECT remove_icd_id remove_true_icd_id, remove_cnt_x  remove_true_cnt, remove_bed_day_x remove_true_bed_day FROM ( \n"
			+" SELECT icd_id remove_icd_id,icd_code remove_icd_code, remove, count(remove) remove_cnt_x, sum(remove_bed_day) remove_bed_day_x \n"
			+" FROM \n"
			+"   (SELECT history_icd10.icd_id, \n"
			+"           history_icd10.icd_code, \n"
			+"           if(remove_to.history_id>0,7,if(result_id=5,9,8)) remove, \n"
			+"           datediff(history_icd10.department_history_out, history_icd10.department_history_in)+1 remove_bed_day \n"
			+"    FROM \n"
			+"      (SELECT department_history_period.*, \n"
			+"              all_department_history_with_icd10.*, \n"
			+"              h.direct_id, \n"
			+"              h.result_id \n"
			+"       FROM patient p, \n"
			+"            history h, \n"
			+"         (SELECT * \n"
			+"          FROM department_history \n"
			+"          WHERE department_id = :department_id  \n"
			+"            AND YEAR(department_history_out)  = :year  \n"
			+"            AND MONTH(department_history_out)  >= :min_month  \n"
			+"            AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"       LEFT JOIN \n"
			+"         (SELECT icd.icd_id, \n"
			+"                 icd.icd_code, \n"
			+"                 icd.icd_name, \n"
			+"                 dh.history_id h2_id \n"
			+"          FROM history_diagnos hd, \n"
			+"               department_history dh, \n"
			+"               icd icd \n"
			+"          WHERE hd.history_id=dh.history_id \n"
			+"            AND department_id = :department_id  \n"
			+"            AND diagnos_id=3 \n"
			+"            AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"       WHERE p.patient_id=h.patient_id \n"
			+"         AND department_history_period.history_id= h.history_id) history_icd10 \n"
			+"    LEFT JOIN department_history remove_to ON history_icd10.history_id = remove_to.history_id \n"
			+"    AND TIMESTAMPDIFF(SECOND,history_icd10.department_history_out,remove_to.department_history_in) = 1 \n"
			+"    ) remove \n"
			+"    GROUP BY icd_id, remove) remove \n"
			+"      WHERE remove = 8 \n"
			+" ) remove_true on remove_true_icd_id = all_icd10_of_department.icd_id \n"
			+" LEFT JOIN ( \n"
			+" SELECT remove_icd_id remove_dead_icd_id, remove_cnt_x  remove_dead_cnt, remove_bed_day_x remove_dead_bed_day FROM ( \n"
			+" SELECT icd_id remove_icd_id,icd_code remove_icd_code, remove, count(remove) remove_cnt_x, sum(remove_bed_day) remove_bed_day_x \n"
			+" FROM \n"
			+"   (SELECT history_icd10.icd_id, \n"
			+"           history_icd10.icd_code, \n"
			+"           if(remove_to.history_id>0,7,if(result_id=5,9,8)) remove, \n"
			+"           datediff(history_icd10.department_history_out, history_icd10.department_history_in)+1 remove_bed_day \n"
			+"    FROM \n"
			+"      (SELECT department_history_period.*, \n"
			+"              all_department_history_with_icd10.*, \n"
			+"              h.direct_id, \n"
			+"              h.result_id \n"
			+"       FROM patient p, \n"
			+"            history h, \n"
			+"         (SELECT * \n"
			+"          FROM department_history \n"
			+"          WHERE department_id = :department_id  \n"
			+"            AND YEAR(department_history_out)  = :year  \n"
			+"            AND MONTH(department_history_out)  >= :min_month  \n"
			+"            AND MONTH(department_history_out)  <= :max_month ) department_history_period \n"
			+"       LEFT JOIN \n"
			+"         (SELECT icd.icd_id, \n"
			+"                 icd.icd_code, \n"
			+"                 icd.icd_name, \n"
			+"                 dh.history_id h2_id \n"
			+"          FROM history_diagnos hd, \n"
			+"               department_history dh, \n"
			+"               icd icd \n"
			+"          WHERE hd.history_id=dh.history_id \n"
			+"            AND department_id = :department_id  \n"
			+"            AND diagnos_id=3 \n"
			+"            AND hd.icd_id=icd.icd_id) all_department_history_with_icd10 ON all_department_history_with_icd10.h2_id=department_history_period.history_id \n"
			+"       WHERE p.patient_id=h.patient_id \n"
			+"         AND department_history_period.history_id= h.history_id) history_icd10 \n"
			+"    LEFT JOIN department_history remove_to ON history_icd10.history_id = remove_to.history_id \n"
			+"    AND TIMESTAMPDIFF(SECOND,history_icd10.department_history_out,remove_to.department_history_in) = 1 \n"
			+"    ) remove \n"
			+"    GROUP BY icd_id, remove) remove \n"
			+"      WHERE remove = 9 \n"
			+" ) remove_dead on remove_dead_icd_id = all_icd10_of_department.icd_id \n"
			;
	public static String bedDayMySql = ""
			+" SELECT d.*, \n"
			+"        round(if(d.dead IS NULL, 0, d.dead/TREAT*100),2) mortality, \n"
			+"        round(bed_day * 100 / bed_day_plan,2) bed_day_fulfil, \n"
			+"        round(bed_day  / department_bed,2)  bed_occupancy, \n"
			+"        round(bed_day  / TREAT,1) treat_avg, \n"
			+"        round((bed_day  / department_bed)/( bed_day / TREAT ),2)  bed_turnover, \n"
			+"         round((d.in_clinic+ifnull(d.dead,0))/d.department_bed,2)  bed_turnover2 \n"
			+" -- FROM \n"
			+" FROM \n"
			+"   (SELECT d.*, \n"
			+"           round((d.in_clinic+ifnull(d.in_dep,0)+d.out_clinic+ifnull(d.out_dep,0)+ifnull(d.dead,0))/2) TREAT \n"
			+"    FROM \n"
			+"      (SELECT d.department_id dp_id, \n"
			+"              d.department_name, \n"
			+"              d.department_bed, \n"
			+"              if(d.department_id=14,310,340) bd_key, \n"
			+"              bed_day_plan, \n"
			+"              in_clinic.in_clinic, \n"
			+"              in_dep.in_dep, \n"
			+"              out_clinic.out_clinic, \n"
			+"              out_dep.out_dep, \n"
			+"              out_to_clinic.out_to_clinic, \n"
			+"              dead.dead, \n"
			+"              bed_day.bed_day \n"
			+"       FROM (-- відділення + розгорнуті ліжка + план ліжкоднів \n"
			+"             SELECT department_id, \n"
			+"                    department_name, \n"
			+"                    department_bed, \n"
			+"                    sum(bed_day_plan) bed_day_plan \n"
			+"             FROM (-- bed_day_plan \n"
			+"                   SELECT *, \n"
			+"                          round(bd_key/366*month_days*department_bed) bed_day_plan \n"
			+"                   FROM (-- відділення з ліжкоднями \n"
			+"                         SELECT d.department_id, \n"
			+"        department_bed, \n"
			+"        d.department_name, \n"
			+"        if(d.department_id=14,310,if(d.department_id=23 or d.department_id=10,290,340)) bd_key \n"
			+" FROM department_bed db1, \n"
			+"      department d, \n"
			+"   (SELECT max(department_bed_id) department_bed_id \n"
			+"    FROM department_bed \n"
			+"    GROUP BY department_id) db2 \n"
			+" WHERE db1.department_bed_id=db2.department_bed_id \n"
			+"   AND d.department_id=db1.department_id) department_bed, \n"
			+"                        (-- днів в місяці \n"
			+"                         SELECT max(day(daydate)) month_days \n"
			+"                         FROM every_day \n"
			+"                         WHERE month(daydate)  >= :min_month  \n"
			+"                           AND month(daydate)  <= :max_month  \n"
			+"                           AND year(daydate) = 2016 \n"
			+"                         GROUP BY month(daydate)) month_days) bed_day_plan \n"
			+"             GROUP BY department_id ) d \n"
			+"       LEFT JOIN (-- поступивші в лікарню \n"
			+"                  SELECT history_department_in, \n"
			+"                         count(history_department_in) in_clinic \n"
			+"                  FROM history \n"
			+"                  WHERE month(history_in)  >= :min_month  \n"
			+"                    AND month(history_in)  <= :max_month  \n"
			+"                    AND year(history_in) = :year  \n"
			+"                  GROUP BY history_department_in) in_clinic ON in_clinic.history_department_in=d.department_id \n"
			+"       LEFT JOIN (-- переведені з інши відділення \n"
			+"                  SELECT dh.department_id, \n"
			+"                         count(dh.department_id) in_dep \n"
			+"                  FROM \n"
			+"                    (SELECT dh.* \n"
			+"                     FROM department_history dh, \n"
			+"                          history h \n"
			+"                     WHERE h.history_id=dh.history_id \n"
			+"                       AND h.history_department_in != dh.department_id) dh \n"
			+"                  WHERE month(dh.department_history_in)  >= :min_month  \n"
			+"                    AND month(dh.department_history_in)  <= :max_month  \n"
			+"                    AND year(dh.department_history_in) = :year  \n"
			+"                  GROUP BY dh.department_id) in_dep ON in_dep.department_id=d.department_id \n"
			+"       LEFT JOIN (-- виписані з лікарні \n"
			+"                  SELECT history_department_out, \n"
			+"                         count(history_department_out) out_clinic \n"
			+"                  FROM history \n"
			+"                  WHERE month(history_out) >= :min_month  \n"
			+"                    AND month(history_out) <= :max_month  \n"
			+"                    AND year(history_out) = :year  \n"
			+"                  GROUP BY history_department_out) out_clinic ON out_clinic.history_department_out=d.department_id \n"
			+"       LEFT JOIN (-- переведені в інші відділення \n"
			+"                  SELECT dh.department_id, \n"
			+"                         count(dh.department_id) out_dep \n"
			+"                  FROM \n"
			+"                    (SELECT dh.* \n"
			+"                     FROM department_history dh, \n"
			+"                          history h \n"
			+"                     WHERE h.history_id=dh.history_id \n"
			+"                       AND h.history_department_out != dh.department_id) dh \n"
			+"                  WHERE month(dh.department_history_out) >= :min_month  \n"
			+"                    AND month(dh.department_history_out) <= :max_month  \n"
			+"                    AND year(dh.department_history_out) = :year  \n"
			+"                  GROUP BY dh.department_id) out_dep ON out_dep.department_id=d.department_id \n"
			+"       LEFT JOIN (-- переведені в іншу лікарню \n"
			+"                  SELECT history_department_out, \n"
			+"                         count(history_department_out) out_to_clinic \n"
			+"                  FROM history h \n"
			+"                  WHERE result_id=6 \n"
			+"                    AND month(history_out) >= :min_month  \n"
			+"                    AND month(history_out) <= :max_month  \n"
			+"                    AND year(history_out) = :year  \n"
			+"                  GROUP BY history_department_out) out_to_clinic ON out_to_clinic.history_department_out=d.department_id \n"
			+"       LEFT JOIN (-- померло \n"
			+"                  SELECT history_department_out, \n"
			+"                         count(history_department_out) dead \n"
			+"                  FROM history \n"
			+"                  WHERE month(history_out) >= :min_month  \n"
			+"                    AND month(history_out) <= :max_month  \n"
			+"                    AND year(history_out) = :year  \n"
			+"                    AND result_id=5 \n"
			+"                  GROUP BY history_department_out) dead ON dead.history_department_out=d.department_id \n"
			+"       LEFT JOIN (-- ліжкодні (сумма лікувались кожного дня) \n"
			+"                  SELECT department_id, \n"
			+"                         sum(TREAT) bed_day \n"
			+"                  FROM (-- лікувальсь в день \n"
			+"                        SELECT department_id, \n"
			+"                               daydate, \n"
			+"                               count(daydate) TREAT \n"
			+"                        FROM department_history dh, \n"
			+"                          (SELECT * \n"
			+"                           FROM every_day \n"
			+"                           WHERE month(daydate)  >= :min_month  \n"
			+"                             AND month(daydate)  <= :max_month  \n"
			+"                             AND year(daydate) = 2016) daydate \n"
			+"                        WHERE daydate>=dh.department_history_in \n"
			+"                          AND daydate<=dh.department_history_out \n"
			+"                        GROUP BY department_id, \n"
			+"                                 daydate) treat_of_day \n"
			+"                  GROUP BY department_id) bed_day ON bed_day.department_id=d.department_id) d)d \n"
			+" UNION \n"
			+" SELECT * \n"
			+" FROM \n"
			+"   (SELECT 0 dp_id, \n"
			+"           'Всього:' department_name, \n"
			+"                     0 d_bed, \n"
			+"                     0 d_bed_plan, \n"
			+"                     0 max_moth_day ) all_, \n"
			+"   (SELECT count(history_department_in) _in \n"
			+"    FROM history \n"
			+"    WHERE month(history_in) >= :min_month  \n"
			+"      AND month(history_in) <= :max_month  \n"
			+"      AND year(history_in) = :year ) in_, \n"
			+"   (SELECT 0 in_dep) in_dep, \n"
			+"   (SELECT count(history_department_out) _out \n"
			+"    FROM history \n"
			+"    WHERE month(history_out) >= :min_month  \n"
			+"      AND month(history_out) <= :max_month  \n"
			+"      AND year(history_out) = :year ) out_, \n"
			+"   (SELECT 0 out_dep) out_dep, \n"
			+"   (SELECT 0 out_to_clinic) out_to_clinic, \n"
			+"   (SELECT count(history_department_out) dead, \n"
			+"      (SELECT 0 l) bed_day, \n"
			+"      (SELECT 0 l) TREAT, \n"
			+"      (SELECT 0 l) mortality, \n"
			+"      0 bed_day_fulfil, \n"
			+" 0     bed_occupancy, \n"
			+" 0     treat_avg, \n"
			+" 0     bed_turnover, \n"
			+" 0     bed_turnover2 \n"
			+"    FROM history \n"
			+"    WHERE month(history_out) >= :min_month  \n"
			+"      AND month(history_out) <= :max_month  \n"
			+"      AND year(history_out) = :year  \n"
			+"      AND result_id=5) dead \n"
			;
	public static String bedDayH2 = ""
			+" SELECT calc3.*, "
			+"        round(bed_occupancy/treat_avg,2) bed_turnover "
			+" FROM "
			+"   (SELECT calc2.*, "
			+"           bed_day*100/bed_day_plan bed_day_fulfil, "
			+"           bed_day*10/DEPARTMENT_BED*.1 bed_occupancy, "
			+"           TREAT*1000/bed_day*.1 treat_avg "
			+"    FROM "
			+"      (SELECT calc1.*, "
			+"              ifnull(dead,0)*1000/TREAT*.1 mortality_procent, "
			+"                                        ym.k*100/ym.yd*ym.month_days*DEPARTMENT_bed/100 bed_day_plan "
			+"       FROM "
			+"         (SELECT d.DEPARTMENT_id dp_id, "
			+"                 d.DEPARTMENT_name, "
			+"                 d.DEPARTMENT_bed, "
			+"                 summ.*, "
			+"                 (summ.in_clinic+ifnull(summ.in_department,0)+ summ.out_clinic + ifnull(summ.out_department,0) + ifnull(summ.dead,0))/2 TREAT "
			+"          FROM hol2.DEPARTMENT d "
			+"          LEFT JOIN "
			+"            (SELECT sum(MOVEDEPARTMENTPATIENT_IN) in_clinic, "
			+"                    sum(MOVEDEPARTMENTPATIENT_INDEPARTMENT) in_department, "
			+"                    sum(MOVEDEPARTMENTPATIENT_OUT) out_clinic, "
			+"                    sum(MOVEDEPARTMENTPATIENT_OUTDEPARTMENT) out_department, "
			+"                    sum(MOVEDEPARTMENTPATIENT_DEAD) dead, "
			+"                    sum(MOVEDEPARTMENTPATIENT_PATIENT2DAY) bed_day, "
			+"                    DEPARTMENT_ID "
			+"             FROM hol2.MOVEDEPARTMENTPATIENT "
			+"             WHERE month(MOVEDEPARTMENTPATIENT_DATE)>=1 "
			+"               AND month(MOVEDEPARTMENTPATIENT_DATE)<=1 "
			+"               AND year(MOVEDEPARTMENTPATIENT_DATE) = :year  "
			+"             GROUP BY DEPARTMENT_ID) summ ON d.DEPARTMENT_id=summ.DEPARTMENT_id "
			+"          ORDER BY d.DEPARTMENT_id) calc1, "
			+"         (SELECT day(dateadd(dd,-day(ym_next),ym_next)) month_days, "
			+"                 CASE WHEN 2016%4 =0 THEN 366 ELSE 365 END yd, "
			+"                                                           280 k "
			+"          FROM "
			+"            (SELECT DATEADD(m,1,ym) ym_next "
			+"             FROM "
			+"               (SELECT parsedatetime(concat(2016,'-',1,'-1'),'yyyy-MM-dd') ym)ym)ym)ym) calc2)calc3 "
;

}
